ctaWEB/Controllers/DashboardController.cs
using ctaCOMMON;
using ctaCOMMON.Charts;
using ctaCOMMON.Dashboard;
using ctaCOMMON.Interface;
using ctaSERVICES;
using ctaWEB.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ctaWEB.Controllers
{
    [Authorize]
    public class DashboardController : Controller
    {
        // GET: Dashboard        
        public ActionResult Index()
        {
            string username = System.Web.HttpContext.Current.User.Identity.Name;
            ViewBag.IsFREEuser = (UserService.GetTenant_Type(username) == 1);
            DashboardModel dashboard = new DashboardModel(username, 0);
            return View(dashboard);            
        }

        public ActionResult SymbolDashboard(string username, int symbol_id, int portfolio_id)
        {
            if (System.Web.HttpContext.Current.User.Identity.Name == username)
            {
                SymbolDashboardModel symb = new SymbolDashboardModel(portfolio_id, symbol_id, username, ChartRange.ThreeMonths, CandelRange.Daily, true); //false: for now true because the quotes are needed to calculate indicator's DisplayValue.
                return View(symb);
            }
            return RedirectToAction("Logout", "User");
        }

        [HttpPost]
        public ActionResult GetSymbolByLabel(string term)
        {
            List<ISimplifiedSearchSymbolResult> data = DashboardService.GetSymbolsByLabel(term);
            return Json(data, JsonRequestBehavior.AllowGet);            
        }        

        [HttpPost]
        public PartialViewResult DashboardAddPortfolio(DashhboardAddPortfolioModel dashboard_add_portfolio)
        {
            if(System.Web.HttpContext.Current.User.Identity.Name == dashboard_add_portfolio.username)
            {
                string action_validation = ValidationService.ValidateUserProtfolioCount(dashboard_add_portfolio.username);
                if (String.IsNullOrEmpty(action_validation))
                    DashboardService.AddPortfolioToDashboard(dashboard_add_portfolio.username, dashboard_add_portfolio.Portfolio_Name);
                else
                    ViewBag.ActionValidationError = action_validation;                
            }            
            return PartialView("~/Views/Dashboard/Partial/Watchlists.cshtml", new DashboardModel(System.Web.HttpContext.Current.User.Identity.Name, 0));
        }

        [HttpPost]
        public PartialViewResult DashboardDeletePortfolio(DashboardModel dashboard_delete_portfolio, string Username)
        {
            if (System.Web.HttpContext.Current.User.Identity.Name == Username)
            {
                DashboardService.DeletePortfolioFromDashboard(Username, dashboard_delete_portfolio.Portfolio_Name);
            }
            return PartialView("~/Views/Dashboard/Partial/Watchlists.cshtml", new DashboardModel(System.Web.HttpContext.Current.User.Identity.Name, 0));
        }

        [HttpPost]
        public PartialViewResult PortfolioAddSymbol(PortfolioAddSymbolModel portfolio_add_symbol)
        {
            if (System.Web.HttpContext.Current.User.Identity.Name == portfolio_add_symbol.Username)
            {
                string action_validation = ValidationService.ValidateUserSymbolCount(portfolio_add_symbol.Username, portfolio_add_symbol.Portfolio_Id);
                if (String.IsNullOrEmpty(action_validation))
                    DashboardService.AddSymbolToPortfolio(portfolio_add_symbol.Portfolio_Id, portfolio_add_symbol.Symbol_Id);
                else
                    ViewBag.ActionValidationError = action_validation;                
            }
            return PartialView("~/Views/Dashboard/Partial/Watchlists.cshtml", new DashboardModel(System.Web.HttpContext.Current.User.Identity.Name, portfolio_add_symbol.Portfolio_Id));
        }

        public RedirectToRouteResult PortfolioDeleteSymbol(PortfolioAddSymbolModel portfolio_add_symbol)
        {
            if (System.Web.HttpContext.Current.User.Identity.Name == portfolio_add_symbol.Username)
            {
                DashboardService.DeleteSymbolFromPortfolio(portfolio_add_symbol.Portfolio_Id, portfolio_add_symbol.Symbol_Id);
            }
            
            return RedirectToAction("Index");            
        }

        public ActionResult GetUserDashboardData() 
        {
            string username = System.Web.HttpContext.Current.User.Identity.Name;
            UserDashboard dashboard = new UserDashboard(username);
            return Json(dashboard.UserDashboardToJSON(), JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetSymbolDashboardData(int symbol_id, int portfolio_id) 
        {
            string username = System.Web.HttpContext.Current.User.Identity.Name;
            SymbolDashboard dashboard = new SymbolDashboard();
            return Json(dashboard.SymbolDashboardToJSON(), JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetSimplifiedSymbolData(int symbol_id, int portfolio_id, string containerid)
        {
            Serie data = DashboardService.GetSymbolDataSerie(symbol_id, portfolio_id, DataSourceFieldUsed.Close);
            Serie intradiaty_data = DashboardService.GetSymbolIntradiaryDataSerie(portfolio_id, symbol_id);

            object dataformated = Serie.GetChartLineFormatedData(data);
            object intradiaryformated = Serie.GetChartLineFormatedData(intradiaty_data);
            object response = new { symbol_id = symbol_id, quotesdata = dataformated, containerid = containerid, quotesintradiary = intradiaryformated };
            return Json(response, JsonRequestBehavior.AllowGet);
        }

        [AllowAnonymous]
        public ActionResult GetSymbolContent(int symbol_id, string main_chart_type, ChartRange chartRange, CandelRange candelRange, int portfolio_id = 0)
        {
            SymbolContentModel symbol_content = new SymbolContentModel(portfolio_id, symbol_id);
            symbol_content.Symbol_Dashboard = DashboardService.GetSymbolDashboard(portfolio_id, symbol_id, chartRange, candelRange, true);            

            object data = symbol_content.GetDataInJSONFormat(main_chart_type);
            object data_series_main_chart = symbol_content.GetDataSeriesInfoForMainChart(main_chart_type);
            object data_view_main_chart = symbol_content.GetDataViewInfoForMainChartData(main_chart_type);
            object volume_chart_view = symbol_content.GetDataViewInfoForVolumeChart(main_chart_type);
            object date_range_selector_view = symbol_content.GetDataViewInfoForDateRangeSelector(main_chart_type);
            object[] data_indicators = symbol_content.GetDataInfoForChartIndicators(main_chart_type);
            object max_data_date = symbol_content.max_date.ToString("r");

            object response = new { data = data, series_main_chart = data_series_main_chart, view_main_chart = data_view_main_chart, indicators = data_indicators, date_range_selector_view = date_range_selector_view, max_data_date = max_data_date, volume_chart_view = volume_chart_view };

            var jsonResult = Json(response, JsonRequestBehavior.AllowGet);
            jsonResult.MaxJsonLength = int.MaxValue;

            return jsonResult;
        }

        [HttpPost]
        public ActionResult AddIndicator(AddIndicatorModel indicator)
        {
            if (System.Web.HttpContext.Current.User.Identity.Name == indicator.username)
            {
                string action_validation = ValidationService.ValidateUserIndicatorCount(indicator.username, indicator.id_portfolio, indicator.id_symbol);
                if (String.IsNullOrEmpty(action_validation))                
                    DashboardService.AddIndicator(indicator.id_portfolio, indicator.id_symbol, indicator.id_indicator, indicator.param1, indicator.color1, indicator.param2, indicator.color2, indicator.param3, indicator.color3);                
                else
                    ViewBag.ActionValidationError = action_validation;
            }
            return PartialView("~/Views/Dashboard/Partial/SymbolDashboardContent.cshtml", new SymbolDashboardModel(indicator.id_portfolio, indicator.id_symbol,indicator.username, ChartRange.ThreeMonths, CandelRange.Daily, true));           
        }

        public ActionResult DeleteIndicator(int indicator_id, string username)
        {
            if (System.Web.HttpContext.Current.User.Identity.Name == username)
            {
                DashboardService.DeleteIndicator(indicator_id);
            }

            object response = new { success = true };
            return Json(response, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult AddShape(AddShapeModel shape)
        {
            if (System.Web.HttpContext.Current.User.Identity.Name == shape.username)
            {
                string action_validation = ValidationService.ValidateUserIndicatorCount(shape.username, shape.id_portfolio, shape.id_symbol);
                if (String.IsNullOrEmpty(action_validation))
                    DashboardService.AddShape(shape.id_portfolio, shape.id_symbol, shape.id_shape, shape.date1, shape.value1, shape.date2, shape.value2, shape.color, shape.name);
                else
                    ViewBag.ActionValidationError = action_validation;
            }
            return PartialView("~/Views/Dashboard/Partial/SymbolDashboardContent.cshtml", new SymbolDashboardModel(shape.id_portfolio, shape.id_symbol, shape.username, ChartRange.ThreeMonths, CandelRange.Daily,true));            
        }

        public ActionResult DeleteShape(int shape_id, string username)
        {
            if (System.Web.HttpContext.Current.User.Identity.Name == username)
            {

ctaWEB/Views/Dashboard/Partial/AddIndicator.cshtml
@model ctaWEB.Models.AddIndicatorModel

<div class="col-md-offset-10 col-md-1" style="padding-left:10px;">
    <a href="#" id="closeX1" onclick="javascript: $('#add_indicator_form').hide(); $('#closeX1').hide();" style="display:none;"><span class="glyphicon glyphicon-remove-circle"></span></a>
</div> 
<div id="add_indicator_form" style="display:none; border: 1px solid #cccccc; padding: 10px; border-radius: 5px;">         
    @using (Ajax.BeginForm("AddIndicator", "Dashboard", new AjaxOptions() { HttpMethod = "POST", OnSuccess = "OnSuccessAddIndicator(data, status, xhr)" }))
    {
        @Html.HiddenFor(m => m.username)
        @Html.HiddenFor(m => m.id_indicator, new { id = "indicator_id" })
        @Html.HiddenFor(m => m.id_portfolio)
        @Html.HiddenFor(m => m.id_symbol)  
        
        <h6>Parámetros</h6>
        <div class="col-md-12" id="param1_container">
            <div class="input-group" style="width:160px;margin-bottom:20px;">
                @Html.LabelFor(m => m.param1, new { id = "param1_label", @class = "input-group-addon" })
                @Html.TextBoxFor(m => m.param1, new { @class = "form-control" })
                <br />
                @Html.ValidationMessageFor(m => m.param1)
            </div>
        </div>
        <div class="col-md-12" id="param2_container">
            <div class="input-group" style="width:160px;margin-bottom:20px;">
                @Html.LabelFor(m => m.param2, new { id = "param2_label", @class = "input-group-addon" })
                @Html.TextBoxFor(m => m.param2, new { @class = "form-control" })
                <br />
                @Html.ValidationMessageFor(m => m.param2)
            </div>
        </div>
        <div class="col-md-12" id="param3_container">
            <div class="input-group" style="width:160px;">
                @Html.LabelFor(m => m.param3, new { id = "param3_label", @class = "input-group-addon" })
                @Html.TextBoxFor(m => m.param3, new { @class = "form-control" })
                <br />
                @Html.ValidationMessageFor(m => m.param3)
            </div>
        </div>        
        <h6>Diseño</h6>
        <div class="col-md-12" id="color1_container">
            <div id="cp1" class="input-group" style="width:160px;border-left-width:1px;border-left-style:solid;border-left-color:#cccccc;">
                @Html.TextBoxFor(m => m.color1, new { id = "indicator_color1", @class = "form-control", style = "cursor:not-allowed;background-color:#eee;display:none;" })
                <span id="indicator_color1_picker" class="input-group-addon" style="cursor:pointer;"><i></i></span>
            </div>
            <br />
            @Html.ValidationMessageFor(m => m.color1)
        </div>
        <div class="col-md-12" id="color2_container">
            <div id="cp2" class="input-group" style="width:160px;border-left-width:1px;border-left-style:solid;border-left-color:#cccccc;">
                @Html.TextBoxFor(m => m.color2, new { id = "indicator_color2", @class = "form-control", style = "cursor:not-allowed;background-color:#eee;display:none;" })
                <span id="indicator_color2_picker" class="input-group-addon" style="cursor:pointer;"><i></i></span>
            </div>
            <br />
            @Html.ValidationMessageFor(m => m.color2)
        </div>
        <div class="col-md-12" id="color3_container">
            <div id="cp3" class="input-group" style="width:160px;border-left-width:1px;border-left-style:solid;border-left-color:#cccccc;">
                @Html.TextBoxFor(m => m.color3, new { id = "indicator_color3", @class = "form-control", style = "cursor:not-allowed;background-color:#eee;display:none;" })
                <span id="indicator_color3_picker" class="input-group-addon" style="cursor:pointer;"><i></i></span>
            </div>
            <br />
            @Html.ValidationMessageFor(m => m.color3)
        </div>        
        <div class="col-md-12" style="margin-top:5px;">
            <button type="submit" class="btn btn-xs" style="background-color:#147063;color:white;"> <i class="glyphicon glyphicon-send"></i> Enviar</button>            
        </div>
    }
</div>

ctaWEB/Views/Dashboard/Partial/AddShape.cshtml
@model ctaWEB.Models.AddShapeModel

<div class="col-md-offset-10 col-md-1" style="padding-left:10px;">
    <a href="#" id="closeX2" onclick="javascript: $('#add_shape_form').hide(); $('#closeX2').hide();" style="display:none;"><span class="glyphicon glyphicon-remove-circle"></span></a>
</div>
<div id="add_shape_form" style="display:none; border: 1px solid #cccccc; padding: 10px; border-radius: 5px;">
    @using (Ajax.BeginForm("AddShape", "Dashboard", new AjaxOptions() { HttpMethod = "POST", OnSuccess = "OnSuccessAddShape(data, status, xhr)" }))
    {
        @Html.HiddenFor(m => m.username)
        @Html.HiddenFor(m => m.id_shape, new { id = "shape_id" })
        @Html.HiddenFor(m => m.id_portfolio)
        @Html.HiddenFor(m => m.id_symbol)
        @Html.HiddenFor(m => m.color, new { id = "shape_color" })
        @Html.HiddenFor(m => m.date1, new { id = "shape_date1" })
        @Html.HiddenFor(m => m.date2, new { id = "shape_date2" })
        @Html.HiddenFor(m => m.value1, new { id = "shape_value1" })
        @Html.HiddenFor(m => m.value2, new { id = "shape_value2" })
        <div class="col-md-12">
            <div class="input-group" style="width:200px;">
                <span class="input-group-addon" id="basic-addon1">Nombre:</span>
                @Html.TextBoxFor(m => m.name, new { id = "rect_name", @class = "form-control" })
            </div>
        </div>
        <div class="col-md-12">            
            <div id="cp4" class="input-group" style="width:200px;border-left-width:1px;border-left-style:solid;border-left-color:#cccccc;">
                <input id="rect_color" type="text" class="form-control" pick-a-color-label-id="COLOR:" style="cursor:not-allowed;background-color:#eee;display:none" />                
                <span id="rect_color_picker" class="input-group-addon" style="cursor:pointer;"><i></i></span>
            </div>
        </div>
        <div class="col-md-12" style="margin-top:5px;">
            <button id="save_shape" type="submit" class="btn btn-xs" style="background-color:#147063;color:white;display:none;"> <i class="glyphicon glyphicon-send"></i> Enviar</button>
        </div>
    }
</div>

ctaWEB/Views/Dashboard/Partial/DashboardAddPortfolio.cshtml
@model ctaWEB.Models.DashhboardAddPortfolioModel

<div id="dashboard_add_portfolio" style="width:100%;">
    @using (Ajax.BeginForm("DashboardAddPortfolio", "Dashboard", new AjaxOptions()
    {
        HttpMethod = "POST",
        //UpdateTargetId = "dashboard_content",        
        LoadingElementId = "updating_dashboard2",
        OnSuccess = "OnSuccessAddPortfolio(data, status, xhr)",
        OnBegin = "$('#submit_add_porfolio').disabled = true;",
        OnComplete = "$('#submit_add_porfolio').disabled = false;"
    }, new { @class = "add_portfolio" }))
    {
        <fieldset>
            @Html.HiddenFor(m => m.username)
            @Html.TextBoxFor(m => m.Portfolio_Name, new { placeholder = "Nombre" })
            @Html.ValidationMessageFor(m => m.Portfolio_Name)
            <input id="submit_add_porfolio" type="submit" value="Enviar" />            
        </fieldset>
    }
</div>

ctaWEB/Views/Dashboard/Partial/DashboardDeletePortfolio.cshtml
@model ctaWEB.Models.DashboardModel

<div id="dashboard_delete_portfolio" style="width:100%;">
    @using (Ajax.BeginForm("DashboardDeletePortfolio", "Dashboard", new AjaxOptions()
    {
        HttpMethod = "POST",
        //UpdateTargetId = "dashboard_content",
        LoadingElementId = "updating_dashboard2",
        OnSuccess = "OnSuccessDeletePortfolio(data, status, xhr)",
        OnBegin = "$('#submit_delete_porfolio').disabled = true;",
        OnComplete = "$('#submit_delete_porfolio').disabled = false;"
    }, new { @class = "add_portfolio" }))
    {
        @Html.HiddenFor(m => m.Username)
        <fieldset>
            @Html.DropDownListFor(m => m.Portfolio_Name,
                                      new SelectList(Model.dashboard_content.Dashboard.DashboardItems, "Portfolio", "Portfolio"),
                                      new {style="width:103px;height:26px;"})
            @Html.ValidationMessageFor(m => m.Portfolio_Name)            
            <input id="submit_delete_porfolio" type="submit" value="Enviar" />            
        </fieldset>
    }
</div>

ctaWEB/Views/Dashboard/Partial/DashboardPortfolioAddSymbol.cshtml
@model ctaWEB.Models.PortfolioAddSymbolModel

<div id="@Model.Portfolio_Id" style="width:100%;">
    @using (Ajax.BeginForm("PortfolioAddSymbol", "Dashboard", new AjaxOptions() { HttpMethod = "POST", @*UpdateTargetId = "dashboard_content",*@ LoadingElementId = "updating_dashboard", OnSuccess = "OnSuccessAddSymbolToPortfolio(data, status, xhr)" }, new { @class = "add_title" }))
    {        
        <fieldset style="border-bottom:1px solid #e5e5e5;padding: 0 0 10px 0;">
            <div id="spinner_container_@Model.Portfolio_Id">
                <!--<legend>Agregar nuevo Título</legend>-->
                @Html.HiddenFor(m => m.Portfolio_Id, new { id = Model.Portfolio_Id })
                @Html.HiddenFor(m => m.Symbol_Id, new { id = "symbol_id_" + Model.Portfolio_Id })
                @Html.HiddenFor(m => m.Username)
                <div class="col-md-8">
                    <input id="symbol_text_@Model.Portfolio_Id" type="text" placeholder="Símbolo..." />
                    @Html.ValidationMessageFor(m => m.Symbol_Id)
                </div>
                <div class="col-md-4">
                    <input id="portfolioAddStockSubmitBtn_@Model.Portfolio_Id" type="submit" value="Agregar" />
                </div>
            </div>            
        </fieldset>        
    }
</div>

<style type="text/css">
    .add_title {
        padding: 10px;
        margin-bottom: 20px;
    }
</style>

ctaWEB/Views/Dashboard/Partial/Reports.cshtml
@model Dictionary<string, List<ctaCOMMON.Dashboard.DashboardReport>>

<ul id="filters" class="nav nav-tabs" role="tablist" style="margin-bottom:5px;">
    @{
        foreach (var reportType in Model.Keys)
        {                
            <li>
                <a href="#@reportType.Replace(' ','_')" data-toggle="tab" class="tab-portfolio-selector">@reportType</a>
            </li>                           
        }
    }
</ul>
<div class="tab-content">
    @{            
        foreach (var reportType in Model.Keys)
        {
            <div class="tab-pane fade" id="@reportType.Replace(' ', '_')">                    
                @{
                    var reports = Model[reportType];
                    reports.Reverse();
                    foreach (var report in reports)
                    {
                        <div class="container" >                        
                            <div class="col-md-12" style="border:solid 1px #E4E4E4;margin-top:20px;margin-bottom:20px;border-radius:5px;">
                                <div class="row">
                                    <div class="col-md-10">
                                        <h3 style="color:#008a69">
                                            <i>@report.title</i>
                                        </h3>
                                    </div>
                                    <div class="col-md-2 text-center">
                                        <h3>
                                            <a href="@report.url" target="_blank" style="font-size:14px;color:#ffffff;padding:10px;background-color:#008a69;border-radius:2px;" title="Open Report">VER INFORME</a>
                                        </h3>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-12 portfolio-symbol-name">
                                        @report.description
                                    </div>
                                </div>
                            </div>
                        </div>
                    }
                }
            </div>            
        }
    }
</div>

ctaWEB/Views/Dashboard/Partial/SymbolContent.cshtml
@model ctaWEB.Models.SymbolContentModel

<style>div.google-visualization-tooltip { width: 150px !important; height: inherit !important;}</style>
<div class="col-md-12">       
    <div id="dashboard" style="margin-top:5px;">
        <div id="combo_chart" class="chart"></div>
        <div id="volume_chart" style="margin-top:-36px;" class="chart"></div>
        <div id="controls" style="margin-top:-19px;margin-bottom:50px;" class="chart"></div>
        <div class="col-lg-12 btn-toolbar" role="toolbar" style="border: 1px solid #E4E4E4;padding:5px;border-radius:5px;margin-top:-45px;text-align:center;">
            <div class="col-lg-offset-4 col-lg-4 btn-group" role="group" style="margin-top:4px;">
                <button id="double_left_arrow" type="button" class="col-lg-3 btn btn-default" style="height:36px;"><img src="~/Images/png/double_left_arrow.png" style="width:100%;height:100%;" /></button>
                <button id="single_left_arrow" type="button" class="col-lg-3 btn btn-default" style="height:36px;"><img src="~/Images/png/single_left_arrow.png" style="width:100%;height:100%;" /></button>
                <button id="single_right_arrow" type="button" class="col-lg-3 btn btn-default" style="height:36px;"><img src="~/Images/png/single_right_arrow.png" style="width:100%;height:100%;" /></button>
                <button id="double_right_arrow" type="button" class="col-lg-3 btn btn-default" style="height:36px;"><img src="~/Images/png/double_right_arrow.png" style="width:100%;height:100%;" /></button>
            </div>
        </div>
        <!--Create elements needded to draw indicators-->
        @foreach (var indicator in Model.Symbol_Dashboard.Indicators)
        {
            if (!indicator.In_Main_Chart)
            {
                <div style="font-size: x-large;">@indicator.DisplayValue</div>
                <div id="@Model.Symbol_Dashboard.Symbol.Symbol_Name.Trim()@indicator.ID" class="chart"></div>
            }
        }   
    </div>
</div>