ctaWEB/Controllers/QuotesController.cs
using ctaCOMMON.Charts;
using ctaSERVICES;
using ctaWEB.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ctaWEB.Controllers
{
    public class QuotesController : BaseController
    {
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Shares()
        {
            return View();
        }

        public ActionResult Options()
        {
            return View();
        }

        public ActionResult Bonds()
        {
            return View();
        }

        public ActionResult Quote(int symbol_id)
        {
            Symbol model = QuotesService.GetSymbolInfo(symbol_id);

            return View(model);
        }

        public ActionResult Indexes()
        {
            return View();
        }


        [HttpPost]
        public PartialViewResult SharesSelector(int marketIndex_id)
        {
            return PartialView("~/Views/Quotes/Partial/SharesWidget.cshtml", new ctaWEB.Models.QuotesSharesModel(1, marketIndex_id));
        }

        [HttpPost]
        public PartialViewResult BondsSelector(int marketIndex_id)
        {
            return PartialView("~/Views/Quotes/Partial/BondsWidget.cshtml", new ctaWEB.Models.QuotesSharesModel(2, marketIndex_id));
        }
    }
}

ctaWEB/Views/Quotes/Partial/Bonds.cshtml
@{
    Layout = null;// "~/Views/Shared/_Layout.cshtml";
}

@*at loading bring the SOBERANOS*@

<div class="container">
    <h2 style="color:#008a69">Bonos</h2>
    <div id="quotes_boxes">
        @Html.Partial("~/Views/Quotes/Partial/BondsWidget.cshtml", new ctaWEB.Models.QuotesSharesModel(2, 8))
    </div>
</div> 

ctaWEB/Views/Quotes/Partial/BondsWidget.cshtml
@model ctaWEB.Models.QuotesSharesModel

<div class="col-md-12" style="z-index:0;position:relative">
    <div class="col-md-12" id="spin2">
        @using (Ajax.BeginForm("BondsSelector", "Quotes", new AjaxOptions() { HttpMethod = "POST", UpdateTargetId = "quotes_boxes" }, new { style = "margin-top:27px;" }))
        {
            <fieldset style="border-bottom:1px solid #e5e5e5;">
                @{
            List<SelectListItem> listItems = new List<SelectListItem>();
            listItems.Add(new SelectListItem
              {
                  Text = "SOBERANOS",
                  Value = "8"
              });
            listItems.Add(new SelectListItem
             {
                 Text = "PROVINCIALES",
                 Value = "9",
             });
            listItems.Add(new SelectListItem
             {
                 Text = "CORPORATIVOS",
                 Value = "10"
             });
                }
                @Html.DropDownListFor(m => m.MarketIndex_ID,
                                        new SelectList(listItems, "Value", "Text"),
                                       new { style = "height:26px;margin-bottom:10px;width:140px;" })

                <input id="submitBT" type="submit" value="Mostrar" />

            </fieldset>
        }
    </div>

    @foreach (var item in Model.GetQuotesValues)
    {
        string bckColor = (item.Variation == 1) ? "green" : ((item.Variation == -1) ? "red" : "blue");
        string variationIcon = (item.Variation == 1) ? "glyphicon-hand-up" : ((item.Variation == -1) ? "glyphicon-hand-down" : "glyphicon-minus");

        <div class="col-xs-12 col-sm-6 col-md-3" style="margin-top:5px;padding-right:0px;padding-left:5px">
            <div class="thumbnail shares-@bckColor wow fadeInUp" data-wow-delay=".1s">
                <div class="caption">
                    <div class="row">
                        <div class="col-md-12" style="text-align:center;">
                            <a href="@Url.Action("Quote", "Quotes", new { symbol_id = item.Symbol_ID })" class="symbol_id_container portfolio-symbol-title" style="color:white">@item.Symbol</a>
                        </div>
                    </div>
                    <div class="row" style="margin-top:11px;color:white">
                        <div class="col-md-3 portfolio-symbol-field-main-value">
                            @item.CurrentAskPrice
                        </div>
                        <div class="col-md-1 col-md-offset-1 portfolio-symbol-field-main-value">
                            <span class="glyphicon @variationIcon" aria-hidden="true" style="float:left;"></span>&nbsp;@item.VariationValue&nbsp;(&nbsp;@string.Format("{0:N2}", item.PercentVariation)%&nbsp;)
                        </div>
                    </div>
                    <div class="row" style="margin-top:5px;color:white">
                        <div class="col-md-3 portfolio-symbol-field-title">
                            <div style="width:100%;float:left;">Apertura</div>
                            <div style="width:100%;float:left;" class="portfolio-symbol-field-value">@item.Opening</div>
                        </div>
                        <div class="col-md-3 col-md-offset-1 portfolio-symbol-field-title">
                            <div style="width:100%;float:left;">Mínimo</div>
                            <div style="width:100%;float:left;" class="portfolio-symbol-field-value">@item.Minimum</div>
                        </div>
                        <div class="col-md-3 col-md-offset-1 portfolio-symbol-field-title">
                            <div style="width:100%;float:left;">Maximo</div>
                            <div style="width:100%;float:left;" class="portfolio-symbol-field-value">@item.Maximum</div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }
</div>
<script type="text/javascript">
        var spinner;
        $(document)
            .ajaxStart(function () {
                var target = document.getElementById('spin2');
                spinner = new Spinner();

                spinner.spin(target);
            })
            .ajaxStop(function () {
                spinner.spin(false);
            });

</script>

ctaWEB/Views/Quotes/Partial/Indexes.cshtml
@{
    Layout = null;// "~/Views/Shared/_Layout.cshtml";
}

@*use el de opciones pork es el mismo*@
<div class="container">
    <h2 style="color:#008a69">Indices</h2>
    @Html.Partial("~/Views/Quotes/Partial/OptionsWidget.cshtml", new ctaWEB.Models.QuotesSharesModel(4, null))
</div> 

ctaWEB/Views/Quotes/Partial/NotAuthorizedModal.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<!-- Modal -->
<div class="modal fade" id="notAuthorizedModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document" style="width:362px">
        <div class="modal-content">
            <form class="form-signin wow fadeInUp">
                <h2 class="form-signin-heading">REGISTRESE EN VICIOUSS</h2>
                <div class="login-wrap" style="padding-bottom:0px;padding-top:10px">
                    <p style="color:rgb(20, 112, 99)">
                        Para utilizar nuestras herramientas debe encontrarse registrado y acceder a la sección <a href="@Url.Action("Index","Dashboard")"><strong>Watchlists</strong></a>.
                    </p>
                    <div style="display:inline-block" id="spin">
                        <button class="btn btn-lg btn-login" data-toggle="modal" data-dismiss="modal" data-target="#registerModal" style="width:139px;margin-right:10px">Registro</button>
                        <button class="btn btn-lg btn-login" style="width:138px;background:#CCCCCC;" data-dismiss="modal">Cerrar</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>


ctaWEB/Views/Quotes/Partial/NotInPortfolioModal.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<!-- Modal -->
<div class="modal fade" id="notInPortfolioModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document" style="width:362px">
        <div class="modal-content">
            <form class="form-signin wow fadeInUp">
                <h2 class="form-signin-heading" style="background:#F6F6F6;color:#000000;">Acceso Incorrecto</h2>
                <div class="login-wrap" style="padding-bottom:0px;padding-top:10px">
                    <p style="color:#1C1C1C;">
                        Para utilizar nuestras herramientas y poder guardar tus análisis ingresa desde <a href="@Url.Action("Index","Dashboard")"><strong>Watchlists</strong></a>
                    </p>
                    <div style="text-align:center;">
                        <button class="btn btn-lg btn-login" style="width:138px;background:#CCCCCC;" data-dismiss="modal">Cerrar</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

<script type="text/javascript">
</script>


ctaWEB/Views/Quotes/Partial/Options.cshtml
@{
    Layout = null;// "~/Views/Shared/_Layout.cshtml";
}

@*at loading bring all the options with no clasifications*@

<div class="container">
    <h2 style="color:#008a69">Opciones</h2>
    @Html.Partial("~/Views/Quotes/Partial/OptionsWidget.cshtml", new ctaWEB.Models.QuotesSharesModel(3, null)) 
</div> 



ctaWEB/Views/Quotes/Partial/OptionsWidget.cshtml
@model ctaWEB.Models.QuotesSharesModel

<div class="col-md-12" style="z-index:0;position:relative">
    @foreach (var item in Model.GetQuotesValues)
    {
        string bckColor = (item.Variation == 1) ? "green" : ((item.Variation == -1) ? "red" : "blue");
        string variationIcon = (item.Variation == 1) ? "glyphicon-hand-up" : ((item.Variation == -1) ? "glyphicon-hand-down" : "glyphicon-minus");

        <div class="col-xs-12 col-sm-6 col-md-3" style="margin-top:5px;padding-right:0px;padding-left:5px">
            <div class="thumbnail shares-@bckColor wow fadeInUp" data-wow-delay=".1s">
                <div class="caption">
                    <div class="row">
                        <div class="col-md-12" style="text-align:center;">
                            <a href="@Url.Action("Quote", "Quotes", new { symbol_id = item.Symbol_ID })" class="symbol_id_container portfolio-symbol-title" style="color:white">@item.Symbol</a>
                        </div>
                    </div>
                    <div class="row" style="margin-top:11px;color:white">
                        <div class="col-md-3 portfolio-symbol-field-main-value">
                            @item.CurrentAskPrice
                        </div>
                        <div class="col-md-1 col-md-offset-1 portfolio-symbol-field-main-value">
                            <span class="glyphicon @variationIcon" aria-hidden="true" style="float:left;"></span>&nbsp;@item.VariationValue&nbsp;(&nbsp;@string.Format("{0:N2}", item.PercentVariation)%&nbsp;)
                        </div>
                    </div>
                    <div class="row" style="margin-top:5px;color:white">
                        <div class="col-md-3 portfolio-symbol-field-title">
                            <div style="width:100%;float:left;">Apertura</div>
                            <div style="width:100%;float:left;" class="portfolio-symbol-field-value">@item.Opening</div>
                        </div>
                        <div class="col-md-3 col-md-offset-1 portfolio-symbol-field-title">
                            <div style="width:100%;float:left;">Mínimo</div>
                            <div style="width:100%;float:left;" class="portfolio-symbol-field-value">@item.Minimum</div>
                        </div>
                        <div class="col-md-3 col-md-offset-1 portfolio-symbol-field-title">
                            <div style="width:100%;float:left;">Maximo</div>
                            <div style="width:100%;float:left;" class="portfolio-symbol-field-value">@item.Maximum</div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }
</div>

ctaWEB/Views/Quotes/Partial/QuoteDetailGraph.cshtml
@model ctaWEB.Models.SymbolDashboardModel

@{
    Layout = null;
    bool isuserlogged = System.Web.HttpContext.Current.User != null && System.Web.HttpContext.Current.User.Identity.IsAuthenticated;
    string modalToShow = "";

    if (isuserlogged)
    { modalToShow = "notInPortfolioModal"; }
    else
    { modalToShow = "notAuthorizedModal"; }
}

<div class="row" style="margin-top:10px;">
    <div class="container">
        <div class="col-lg-12 btn-toolbar" role="toolbar" style="border: 1px solid #E4E4E4;padding:5px;border-radius:5px;">
            <div class="btn-group" role="group">
                <button type="button" class="btn btn-default" data-toggle="modal" data-target="#@modalToShow"><img src="~/Images/png/chart_candel.png" /></button>
                <button type="button" class="btn btn-default" data-toggle="modal" data-target="#@modalToShow"><img src="~/Images/png/chart_line.png" /></button>
            </div>
            <div class="btn-group" role="group">
                <button type="button" class="btn btn-default" data-toggle="modal" data-target="#@modalToShow"><img src="~/Images/png/arrow_up.png" /></button>
                <button type="button" class="btn btn-default" data-toggle="modal" data-target="#@modalToShow"><img src="~/Images/png/arrow_down.png" /></button>
                <button type="button" class="btn btn-default" data-toggle="modal" data-target="#@modalToShow"><img src="~/Images/png/arrow_right.png" /></button>
                <button type="button" class="btn btn-default" data-toggle="modal" data-target="#@modalToShow"><img src="~/Images/png/arrow_left.png" /></button>
            </div>
            <div class="btn-group" role="group">
                <button type="button" class="btn btn-default" data-toggle="modal" data-target="#@modalToShow"><img src="~/Images/png/chart_indicator.png" /></button>
                <div class="btn-group">
                    <button class="btn btn-default dropdown-toggle" type="button" data-toggle="modal" data-target="#@modalToShow">
                        <img src="~/Images/png/toolbar_empty.png" width="1" height="20" />
                        <span class="caret"></span>
                    </button>
                </div>
            </div>
            <div class="btn-group" role="group">
                <button type="button" class="btn btn-default" data-toggle="modal" data-target="#@modalToShow"><img src="~/Images/png/chart_shape.png" /></button>
                <div class="btn-group">
                    <button class="btn btn-default dropdown-toggle" type="button" data-toggle="modal" data-target="#@modalToShow">
                        <img src="~/Images/png/toolbar_empty.png" width="1" height="20" />
                        <span class="caret"></span>
                    </button>
                </div>
            </div>
        </div>
        @Html.Partial("~/Views/Dashboard/Partial/SymbolContent.cshtml", Model.symbol_content)
    </div>
</div>
@Html.Partial("~/Views/Quotes/Partial/NotAuthorizedModal.cshtml")
@Html.Partial("~/Views/Quotes/Partial/NotInPortfolioModal.cshtml")

ctaWEB/Views/Quotes/Partial/Shares.cshtml
@{
    Layout = null;// "~/Views/Shared/_Layout.cshtml";
}

@*at loading bring shares of type MERVAL*@

<div class="container">
    <h2 style="color:#008a69">Acciones</h2>
    <div id="quotes_boxes">
        @Html.Partial("~/Views/Quotes/Partial/SharesWidget.cshtml", new ctaWEB.Models.QuotesSharesModel(1, 1))
    </div>
</div>   

ctaWEB/Views/Quotes/Partial/SharesWidget.cshtml
@model ctaWEB.Models.QuotesSharesModel

    <div class="col-md-12" style="z-index:0;position:relative">
        <div class="col-md-12" id="spin2">
            @using (Ajax.BeginForm("SharesSelector", "Quotes", new AjaxOptions() { HttpMethod = "POST", UpdateTargetId = "quotes_boxes" }, new { style = "margin-top:27px;" }))
            {
                <fieldset style="border-bottom:1px solid #e5e5e5;">
                    @{
                List<SelectListItem> listItems = new List<SelectListItem>();
                listItems.Add(new SelectListItem
                  {
                      Text = "MERVAL",
                      Value = "1"
                  });
                listItems.Add(new SelectListItem
                 {
                     Text = "PANEL GENERAL",
                     Value = "2",
                 });
                listItems.Add(new SelectListItem
                 {
                     Text = "MERVAL 25",
                     Value = "3"
                 });
                listItems.Add(new SelectListItem
                {
                    Text = "MERVAL ARG",
                    Value = "4"
                });
                listItems.Add(new SelectListItem
                {
                    Text = "ADRs",
                    Value = "5"
                });
                listItems.Add(new SelectListItem
                {
                    Text = "CEDEARS",
                    Value = "6"
                });
                    }
                    @Html.DropDownListFor(m => m.MarketIndex_ID,
                                        new SelectList(listItems, "Value", "Text"),
                                       new { style = "height:26px;margin-bottom:10px;width:140px;" })

                    <input id="submitBT" type="submit" value="Mostrar" />

                </fieldset>
            }
        </div>

        @foreach (var item in Model.GetQuotesValues)
        {
            string bckColor = (item.Variation == 1) ? "green" : ((item.Variation == -1) ? "red" : "blue");
            string variationIcon = (item.Variation == 1) ? "glyphicon-hand-up" : ((item.Variation == -1) ? "glyphicon-hand-down" : "glyphicon-minus");

            <div class="col-xs-12 col-sm-6 col-md-3" style="margin-top:5px;padding-right:0px;padding-left:5px">
                <div class="thumbnail shares-@bckColor wow fadeInUp" data-wow-delay=".1s">
                    <div class="caption">
                        <div class="row">
                            <div class="col-md-12" style="text-align:center;">
                                <a href="@Url.Action("Quote", "Quotes", new { symbol_id = item.Symbol_ID })" class="symbol_id_container portfolio-symbol-title" style="color:white">@item.Symbol</a>
                            </div>
                        </div>
                        <div class="row" style="margin-top:11px;color:white">
                            <div class="col-md-3 portfolio-symbol-field-main-value">
                                @item.CurrentAskPrice
                            </div>
                            <div class="col-md-1 col-md-offset-1 portfolio-symbol-field-main-value">
                                <span class="glyphicon @variationIcon" aria-hidden="true" style="float:left;"></span>&nbsp;@item.VariationValue&nbsp;(&nbsp;@string.Format("{0:N2}", item.PercentVariation)%&nbsp;)
                            </div>
                        </div>
                        <div class="row" style="margin-top:5px;color:white">
                            <div class="col-md-3 portfolio-symbol-field-title">
                                <div style="width:100%;float:left;">Apertura</div>
                                <div style="width:100%;float:left;" class="portfolio-symbol-field-value">@item.Opening</div>
                            </div>
                            <div class="col-md-3 col-md-offset-1 portfolio-symbol-field-title">
                                <div style="width:100%;float:left;">Mínimo</div>
                                <div style="width:100%;float:left;" class="portfolio-symbol-field-value">@item.Minimum</div>
                            </div>
                            <div class="col-md-3 col-md-offset-1 portfolio-symbol-field-title">
                                <div style="width:100%;float:left;">Maximo</div>
                                <div style="width:100%;float:left;" class="portfolio-symbol-field-value">@item.Maximum</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        }
     </div>
    <script type="text/javascript">
        var spinner;
        $(document)
            .ajaxStart(function () {
                var target = document.getElementById('spin2');
                spinner = new Spinner();

                spinner.spin(target);
            })
            .ajaxStop(function () {
                spinner.spin(false);
            });

    </script>
