ctaWEB/Controllers/AdminStockQuotesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ctaWEB.Models;
using ctaWEB.Models.AdminModels;
using ctaSERVICES;
using ctaCOMMON.Charts;
using ctaCOMMON.DataParser;
using ctaSERVICES.Reporting;

namespace ctaWEB.Controllers
{
    [Authorize(Users = "amed,jgrau,boby")]
    public class AdminStockQuotesController : Controller
    {
        private ctaWEBAdminContext db = new ctaWEBAdminContext();

        [HttpPost]
        public string ClearIntradiary(string market_name)
        {
            try
            {
                QuotesService.ClearIntradiaryDataByMarketID(market_name);
            }
            catch (Exception ex)
            {
                return "ERROR Deleting Intradiary:\n " + ex.Message;
            }
            return "Intradiary Deleted";
        }

        [HttpPost]
        public ActionResult ReadDataFromCSV(HttpPostedFileBase csvdatafile)
        {
            QuotesService.ReadHistoricalDataFromCSV(csvdatafile.InputStream, csvdatafile.FileName);
            return RedirectToAction("Index"); 
        }

        [AllowAnonymous]
        [HttpPost]
        public string RunDailyReportUpdate(string batch)
        {
            string result = "";

            try
            {                
                ReportData_Generator generator = new ReportData_Generator();
                generator.GenerateReportData(batch);                    
            }
            catch (Exception ex)
            {
                result += "\nError: " + ex.InnerException != null ? ex.InnerException.Message : ex.Message;
                ctaCOMMON.EmailSender.SendErrorUpdatingReport(result, DateTime.Now);
            }

            return result += "\nReport Updated";
        }

        [HttpPost]
        public string DeleteReportData()
        {
            try
            {
                ReportData_Generator generator = new ReportData_Generator();
                generator.DeleteReportData();
            }
            catch (Exception ex)
            {
                return "ERROR Deleting Report Data:\n " + ex.Message;
            }
            return "Todays Report Data Deleted";
        }

        [AllowAnonymous]
        [HttpPost]        
        public string RunIntradiaryUpdate(string market_name)
        {
            string result = "";
            //foreach (var market in MarketService.GetMarkets().Where(m => m.name.ToLower() == market_name.ToLower() || market_name.ToUpper() == "ALL"))
            //{
            //    bool error = false;
            //    int utc_offset = ConfigService.GetConfigs().Where(c => c.ConfigName == market.name + "_UTCOffset").Select(c => int.Parse(c.ConfigValue)).FirstOrDefault();
            //    result += market.name.ToUpper() + "\n" + QuotesService.ReadMarketIntradiaryData(market.name, market.Id, utc_offset, out error) + "\n\n";

            //    //Update SyncTime
            //    QuotesService.UpdateQuotesSyncNextTime(market.name, DateTime.UtcNow.AddHours(utc_offset), error);
            //}
            return result;
        }

        [HttpPost]
        public string RunHistoricalUpdate(int stockid, string startdate, string enddate)
        {
            string result = "";
            if (startdate != "" && enddate != "" && stockid != 0)
            {
                try
                {
                    Symbol symbol = QuotesService.GetSymbolInfo(stockid);
                    DateTime start = DateTime.Parse(startdate);
                    DateTime end = DateTime.Parse(enddate);
                    result += symbol.Symbol_Name.ToUpper() + "\nStartDate: " + startdate + "\nEndDate: " + enddate;
                    QuotesService.ReadHistoricalData(start, end, symbol.Symbol_Name, symbol.Symbol_ID);
                }
                catch (Exception ex)
                {
                    return result += "\nError: " + ex.Message;
                }
            }
            return result += "\nHistorical Updated";
        }

        // GET: AdminStockQuotes
        public ActionResult Index(int stockid = 0)
        {
            ViewBag.stock_id = new SelectList(db.GetStocks().Where(s => s.active && s.market_id != 1).OrderBy(s => s.symbol), "Id", "symbol_market");
            ViewBag.SyncMarketInfo = QuotesService.GetMarketsSyncTimeInfo();
            return View(db.GetStockQuotes(stockid).OrderByDescending(s => s.date_round));
        }        

        // GET: AdminStockQuotes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            AdminStockQuotesModel adminStockQuotesModel = db.GetStockQuotes().Where(s => s.Id == id).FirstOrDefault();            

            if (adminStockQuotesModel == null)
            {
                return HttpNotFound();
            }
            return View(adminStockQuotesModel);
        }

        // GET: AdminStockQuotes/Create
        public ActionResult Create()
        {
            ViewBag.stock_id = new SelectList(db.GetStocks(), "Id", "symbol_market");
            return View();
        }

        // POST: AdminStockQuotes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,stock_id,opening,closing,minimun,maximun,volume,date_round,adj_close")] AdminStockQuotesModel adminStockQuotesModel)
        {
            if (ModelState.IsValid)
            {
                //db.AdminStockQuotesModels.Add(adminStockQuotesModel);
                //db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.stock_id = new SelectList(db.GetStocks(), "Id", "symbol_market", adminStockQuotesModel.stock_id);
            return View(adminStockQuotesModel);
        }

        // GET: AdminStockQuotes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AdminStockQuotesModel adminStockQuotesModel = db.GetStockQuotes().Where(s => s.Id == id).FirstOrDefault();
            if (adminStockQuotesModel == null)
            {
                return HttpNotFound();
            }
            ViewBag.stock_id = new SelectList(db.GetStocks(), "Id", "symbol_market", adminStockQuotesModel.stock_id);
            return View(adminStockQuotesModel);
        }

        // POST: AdminStockQuotes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,stock_id,opening,closing,minimun,maximun,volume,date_round,adj_close")] AdminStockQuotesModel adminStockQuotesModel)
        {
            if (ModelState.IsValid)
            {
                //db.Entry(adminStockQuotesModel).State = EntityState.Modified;
                //db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.stock_id = new SelectList(db.GetStocks(), "Id", "symbol_market", adminStockQuotesModel.stock_id);
            return View(adminStockQuotesModel);
        }

        // GET: AdminStockQuotes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AdminStockQuotesModel adminStockQuotesModel = db.GetStockQuotes().Where(s => s.Id == id).FirstOrDefault();
            if (adminStockQuotesModel == null)
            {
                return HttpNotFound();
            }
            return View(adminStockQuotesModel);
        }

        // POST: AdminStockQuotes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            AdminStockQuotesModel adminStockQuotesModel = db.GetStockQuotes().Where(s => s.Id == id).FirstOrDefault();
            //db.AdminStockQuotesModels.Remove(adminStockQuotesModel);
            //db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);
        }
    }
}

ctaWEB/Views/AdminStockQuotes/Create.cshtml
@model ctaWEB.Models.AdminModels.AdminStockQuotesModel

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>AdminStockQuotesModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.stock_id, "stock_id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("stock_id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.stock_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.opening, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.opening, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.opening, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.closing, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.closing, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.closing, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.minimun, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.minimun, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.minimun, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.maximun, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.maximun, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.maximun, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.volume, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.volume, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.volume, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.date_round, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.date_round, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.date_round, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.adj_close, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.adj_close, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.adj_close, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ctaWEB/Views/AdminStockQuotes/Delete.cshtml
@model ctaWEB.Models.AdminModels.AdminStockQuotesModel

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>AdminStockQuotesModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.AdminStocksModel.symbol)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AdminStocksModel.symbol)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.opening)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.opening)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.closing)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.closing)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.minimun)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.minimun)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.maximun)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.maximun)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.volume)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.volume)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.date_round)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.date_round)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.adj_close)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.adj_close)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ctaWEB/Views/AdminStockQuotes/Details.cshtml
@model ctaWEB.Models.AdminModels.AdminStockQuotesModel

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Details</h2>

<div>
    <h4>AdminStockQuotesModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.AdminStocksModel.symbol)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AdminStocksModel.symbol)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.opening)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.opening)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.closing)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.closing)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.minimun)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.minimun)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.maximun)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.maximun)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.volume)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.volume)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.date_round)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.date_round)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.adj_close)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.adj_close)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ctaWEB/Views/AdminStockQuotes/Edit.cshtml
@model ctaWEB.Models.AdminModels.AdminStockQuotesModel

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>AdminStockQuotesModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.stock_id, "stock_id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("stock_id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.stock_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.opening, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.opening, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.opening, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.closing, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.closing, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.closing, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.minimun, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.minimun, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.minimun, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.maximun, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.maximun, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.maximun, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.volume, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.volume, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.volume, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.date_round, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.date_round, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.date_round, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.adj_close, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.adj_close, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.adj_close, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ctaWEB/Views/AdminStockQuotes/Index.cshtml
@model IEnumerable<ctaWEB.Models.AdminModels.AdminStockQuotesModel>

@{
    ViewBag.Title = "Stock Quotes Administration";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<p style="border: 1px dashed green;float:left;margin:10px">
    @Html.ActionLink("Create New", "Create")    
</p>
<h4 style="clear: left;"></h4>

<div id="spinnerContainer" style="border: solid 1px #808080;padding:10px;float:left;margin: 10px;float:left;">
    <h4 style="font-size:large;color:#147063">SYNCHRONIZATION STATUS</h4>
    <table>
        <tr>
            <th><button class="RunIntradiaryUpdate btn-success" market-name="ALL" title="Update All markets"><b><span class="glyphicon glyphicon-download-alt"></span></b></button></th>
            <th>Market</th>
            <th>LastSync</th>
            <th>NextSync</th>
            <th><button class="ClearIntradiary btn-danger" market-name="ALL" title="Delete All markets Intradiary"><b><span class="glyphicon glyphicon-trash"></span></b></button></th>
        </tr>
    @foreach (ctaSERVICES.MarketSyncInfo item in ViewBag.SyncMarketInfo)
    {
        <tr>
            <td><button class="RunIntradiaryUpdate" market-name="@item.Market" title="Update @item.Market" style="color:#5cb85c;"><span class="glyphicon glyphicon-download-alt"></span></button>&nbsp;&nbsp;</td>
            <td><b>@item.Market</b>&nbsp;&nbsp;</td>
            <td style="color:green">@item.LastSync&nbsp;&nbsp;</td>
            <td style="color:orangered">@item.NextSync&nbsp;&nbsp;</td>
            <td><button class="ClearIntradiary" market-name="@item.Market" title="Delete @item.Market Intradiary" style="color:#d9534f;"><span class="glyphicon glyphicon-trash"></span></button>&nbsp;&nbsp;</td>
        </tr>
    }
    </table>
</div>
<h4 style="clear: left;"></h4>

<div style="border: solid 1px #808080;padding:10px;float:left;margin: 10px;">
    <h4 style="font-size:large;color:#147063">UPDATE HISTORICAS FROM CSV FILE</h4>
    <h6>* CSV less than 1MB</h6>
    <h6>* CSV file name have to be Market Name</h6>
    <h6>* CSV file only can contains stocks that belongs to one Market</h6>
    @using (Html.BeginForm("ReadDataFromCSV",
                            "AdminStockQuotes",
                            FormMethod.Post,
                            new { enctype = "multipart/form-data" }))
    {
        <label for="csvdatafile" style="float:left;">Select CSV File:</label>
        <input type="file" name="csvdatafile" id="csvdatafile" style="float:left;"/><input type="submit" value="ENVIAR" style="float:left;" />    
    }
</div>
<h4 style="clear: left;"></h4>

<div style="border: solid 1px #808080;margin:10px;float:left;">
    &nbsp;<b style="font-size:large;color:#147063">UPDATE HISTORICAS:</b>&nbsp;  
    &nbsp;Symbol:&nbsp;@Html.DropDownList("stock_id", null, htmlAttributes: new { id = "stocks" })
    &nbsp;Start Date:&nbsp;<input type="date" id="startdate" />
    &nbsp;End Date:&nbsp;<input type="date" id="enddate" />
    &nbsp;<button class="RunHistoricalUpdate" style="color:#147063"><b>UPDATE</b></button>&nbsp;
</div>
<h4 style="clear: left;"></h4>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.AdminStocksModel.symbol)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.opening)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.closing)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.minimun)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.maximun)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.volume)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.date_round)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.adj_close)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.AdminStocksModel.symbol)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.opening)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.closing)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.minimun)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.maximun)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.volume)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.date_round)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.adj_close)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

<script type="text/javascript">


    $(document).ready(function () {
        $('.RunHistoricalUpdate').click(function () {
            ShowSpinner();
            DisableButton($(this));
            var selected = '';
            $("select option:selected").each(function () {
                selected = $(this).attr('value');
            });
            $.post('@Url.Action("ScheduleHistoryTask", "VcssTaskManager")',
                {
                    stockid: selected,
                    startdate: $('#startdate').val(),
                    enddate: $('#enddate').val()
                },
                function (data, status) {
                    if (data.Success) {
                            alert(data.TaskInfoId + " escheduled.\nStatus: " + status);
                        }
                    else {
                        alert("ERROR!!!\nMessage: " + data.Message);
                    }                    
                    HideSpinner();
                    EnableButton();                                     
                });
        });
        $('.RunIntradiaryUpdate').click(function () {
            ShowSpinner();
            DisableButton($(this));
            var marketname = $(this).attr('market-name')
            if (marketname == 'ReportDATA') {
                $.post('@Url.Action("RunDailyReportUpdate")',
                    {
                        batch: "Batch-1"
                    },
                    function (data, status) {
                        $.post('@Url.Action("RunDailyReportUpdate")',
                            {
                                batch: "Batch-2"
                            },
                            function (data, status) {
                                $.post('@Url.Action("RunDailyReportUpdate")',
                                    {
                                        batch: "Batch-3"
                                    },
                                    function (data, status) {
                                        $.post('@Url.Action("RunDailyReportUpdate")',
                                            {
                                                batch: "Batch-4" 
                                            },
                                            function (data, status) {
                                                $.post('@Url.Action("RunDailyReportUpdate")',
                                                {
                                                    batch: "Batch-5" 
                                                },
                                                function (data, status) {
                                                    $.post('@Url.Action("RunDailyReportUpdate")',
                                                    {
                                                        batch: "Batch-6" 
                                                    },
                                                    function (data, status) {
                                                        alert(data + "\nStatus: " + status);
                                                        HideSpinner();
                                                        EnableButton();
                                                    });
                                                });
                                            });
                                    });
                            });
                    });
            }
            else {
                $.post('@Url.Action("InitializeSchedulers", "VcssTaskManager")',
                {},
                function (data, status) {
                    alert(data + "\nStatus: " + status);
                    HideSpinner();
                    EnableButton();
                });
            }
        });
        $('.ClearIntradiary').click(function () {
            ShowSpinner();
            DisableButton($(this));
            var marketname = $(this).attr('market-name')
            if (marketname == 'ReportDATA') {
                $.post('@Url.Action("DeleteReportData")',
                    function (data, status) {
                        alert(data + "\nStatus: " + status);
                        HideSpinner();
                        EnableButton();
                    });
            }
            else {
                $.post('@Url.Action("ClearIntradiary")',
                {
                    market_name: $(this).attr('market-name')
                },
                function (data, status) {
                    alert(data + "\nStatus: " + status);
                    HideSpinner();
                    EnableButton();
                });
            }
        });
    });

    var spinner;
    function ShowSpinner(){
        spinner = new Spinner({ length: 40, radius: 20, left: '57%', top: '48%', color: '#147063' }).spin(document.getElementById("spinnerContainer"));
    }
    function HideSpinner() {
        if (spinner)
            spinner.spin(false);
    }

    var currentBtn;
    function DisableButton(btn) {
        currentBtn = btn;
        currentBtn.attr("disabled", true);
    }
    function EnableButton() {
        currentBtn.attr("disabled", false);
    }
</script>